Repository awnumar/memguard, pull requests merged in 2019-07, with the labels that each got.

#95 patch: make immutable buffers mutable before wiping
  core/exit.go
Labels: patch

#96 Use fast local csprng
  core/buffer.go
  core/coffer.go
  go.mod
  go.sum
  vendor/gitlab.com/NebulousLabs/fastrand/LICENSE
  vendor/gitlab.com/NebulousLabs/fastrand/README.md
  vendor/gitlab.com/NebulousLabs/fastrand/fastrand.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_386.go
  vendor/golang.org/x/sys/unix/ztypes_linux_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mipsle.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
  vendor/golang.org/x/sys/unix/ztypes_linux_sparc64.go
  vendor/modules.txt
Labels: performance

#97 Wipe partition hash after replacing it
  core/coffer.go
Labels: security

#98 feature: construct buffer from entire reader
  buffer.go
  buffer_test.go
Labels: feature

#101 Add function allowing update of Coffer re-key interval
  core/coffer.go
  core/coffer_test.go
Labels: performance

#102 Simplify usage by returning quasi-destroyed objects instead of panicking
  buffer.go
  buffer_test.go
  core/coffer.go
  core/enclave.go
  core/exit_test.go
  enclave.go
  enclave_test.go
Labels: api-change, ergonomics

#103 Optimise buffer state checks
  buffer.go
  buffer_test.go
  core/buffer.go
  core/buffer_test.go
  core/coffer.go
  core/exit_test.go
Labels: performance

#105 patch: acquire full lock in freeze/melt
  core/buffer.go
  core/enclave.go
Labels: patch

#106 Various fixes
  AUTHORS
  core/crypto.go
Labels: patch, security
